import type { ArticleState } from "./types";
import { STATE_COLOR } from "./constants";

export const ARTICLE_LIFECYCLE_STATES: ArticleState[] = [
  {
    id: "idea",
    name: "ایده",
    description: "موضوع مقاله در حد یک ایده اولیه است.",
    allowedTransitions: ["research", "canceled"],
    color: STATE_COLOR.neutral,
    icon: "lightbulb",
  },
  {
    id: "research",
    name: "تحقیق",
    description: "جمع‌آوری منابع و اطلاعات علمی برای مقاله.",
    allowedTransitions: ["writing", "canceled"],
    color: STATE_COLOR.neutral,
    icon: "search",
  },
  {
    id: "writing",
    name: "نگارش",
    description: "متن مقاله در حال نوشته شدن است.",
    allowedTransitions: ["imported", "canceled"],
    color: STATE_COLOR.neutral,
    icon: "pencil",
  },
  {
    id: "imported",
    name: "وارد شده",
    description: "متن خام مقاله وارد سیستم شده است.",
    allowedTransitions: ["parsed", "canceled"],
    color: STATE_COLOR.info,
    icon: "upload",
  },
  {
    id: "parsed",
    name: "پارس شده",
    description: "متن به بخش‌های ساختاریافته تجزیه شده است.",
    allowedTransitions: ["analyzed", "canceled"],
    color: STATE_COLOR.info,
    icon: "list",
  },
  {
    id: "analyzed",
    name: "تحلیل‌شده",
    description: "تحلیل اولیه محتوا انجام شده است.",
    allowedTransitions: ["seo_optimized", "canceled"],
    color: STATE_COLOR.info,
    icon: "chart",
  },
  {
    id: "seo_optimized",
    name: "بهینه سئو",
    description: "پیشنهادهای سئو بررسی شده‌اند.",
    allowedTransitions: ["aeo_optimized", "canceled"],
    color: STATE_COLOR.info,
    icon: "seo",
  },
  {
    id: "aeo_optimized",
    name: "بهینه AEO",
    description: "پیشنهادهای موتورهای پاسخ بررسی شده‌اند.",
    allowedTransitions: ["geo_optimized", "canceled"],
    color: STATE_COLOR.info,
    icon: "answer",
  },
  {
    id: "geo_optimized",
    name: "بهینه GEO",
    description: "پیشنهادهای موتورهای هوش مصنوعی بررسی شده‌اند.",
    allowedTransitions: ["scientific_review", "canceled"],
    color: STATE_COLOR.info,
    icon: "ai",
  },
  {
    id: "scientific_review",
    name: "بازبینی علمی",
    description: "صحت علمی و منابع مقاله بررسی می‌شود.",
    allowedTransitions: ["human_review", "canceled"],
    color: STATE_COLOR.review,
    icon: "flask",
  },
  {
    id: "human_review",
    name: "بازبینی انسانی",
    description: "مقاله در انتظار بازبینی نهایی توسط مدیر است.",
    allowedTransitions: ["approved", "canceled"],
    color: STATE_COLOR.review,
    icon: "eye",
  },
  {
    id: "approved",
    name: "تأیید شده",
    description: "مقاله برای انتشار تأیید شده است.",
    allowedTransitions: ["scheduled", "published", "canceled"],
    color: STATE_COLOR.success,
    icon: "check",
  },
  {
    id: "scheduled",
    name: "زمان‌بندی شده",
    description: "زمان انتشار مقاله مشخص شده است.",
    allowedTransitions: ["published", "canceled"],
    color: STATE_COLOR.success,
    icon: "calendar",
  },
  {
    id: "published",
    name: "منتشر شده",
    description: "مقاله در سایت منتشر شده است.",
    allowedTransitions: ["updated", "needs_refresh", "archived"],
    color: STATE_COLOR.success,
    icon: "globe",
  },
  {
    id: "updated",
    name: "به‌روزرسانی شده",
    description: "مقاله منتشرشده ویرایش شده است.",
    allowedTransitions: ["published", "needs_refresh", "archived"],
    color: STATE_COLOR.success,
    icon: "refresh",
  },
  {
    id: "needs_refresh",
    name: "نیازمند به‌روزرسانی",
    description: "مقاله بر اساس معیارهای Content Decay نیاز به بازبینی دارد.",
    allowedTransitions: ["updated", "archived"],
    color: STATE_COLOR.review,
    icon: "alert",
  },
  {
    id: "archived",
    name: "بایگانی‌شده",
    description: "مقاله از انتشار فعال خارج شده اما حذف نشده است.",
    allowedTransitions: ["published"],
    color: STATE_COLOR.neutral,
    icon: "archive",
  },
  {
    id: "canceled",
    name: "لغو شده",
    description: "روند تولید این مقاله متوقف شده است. حالت پایانی است.",
    allowedTransitions: [],
    color: STATE_COLOR.danger,
    icon: "x",
  },
];

export const ARTICLE_LIFECYCLE_STATE_MAP: Record<string, ArticleState> = Object.fromEntries(
  ARTICLE_LIFECYCLE_STATES.map((state) => [state.id, state])
);
